# This is a basic workflow to help you get started with Actions
name: AVR build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: bazhenov/action-avr-make@v1.0

